# Generated by Django 4.0.7 on 2022-10-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
